Anime:
  type: object
  config:
    name: Anime
    description: 'An Anime'
    fields:
      malId:
        type: 'ID'
        description: 'Get the associated MyAnimeList ID'
      title:
        type: 'AnimeTitle!'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Anime\\AnimeTitleResolver", [value])'
      url:
        type: 'String'
      imageUrl:
        type: 'String'
      bannerImageUrl:
        type: 'String'
      related:
        type: '[RelatedAnimeRecommendation!]!'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Anime\\RelatedAnimeRecommendationsResolver", [value, args])'
        description: 'Get a list of anime recommendations that explains why the anime has been recommended.'
        args:
          first:
            type: 'Int'
            defaultValue: 3
      description:
        type: 'String'
      slug:
        type: 'String!'
      episodesCount:
        type: 'Int!'
      airing:
        type: 'Boolean!'
      score:
        type: 'Float!'
      trailerUrl:
        type: 'String'
      status:
        type: 'String!'
      duration:
        type: 'String'
      rating:
        type: 'String!'
      synonyms:
        type: '[String!]!'
      type:
        type: 'String!'
      rank:
        type: 'Int!'
      popularity:
        type: 'Int!'
      openingThemes:
        type: '[String!]!'
      endingThemes:
        type: '[String!]!'
      broadcast:
        type: 'String'
