Query:
  type: object
  config:
    name: Query
    fields:
      animelist:
        description: 'Get the animelist of a user'
        type: '[Anime!]!'
        #If you want to use a Relay connection
        #argsBuilder: Relay::Connection
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\AnimelistResolver", [args])'
        args:
          username:
            type: String!
      recommendations:
        description: 'Get recommendations'
        type: '[Anime!]!'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\RecommendationsResolver", [args])'
        args:
          username:
            type: String!
          first:
            type: Int
            defaultValue: 100
      anime:
        description: 'Get anime by its slug'
        type: 'Anime'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\AnimeResolver", [args])'
        args:
          slug:
            type: String!
